### ISSUE TITLE
Crashes Server on 1.21.3

### ISSUE THREAD

**Issue by Mqxx** [JMReich/Path_To_Grass#3]
Hey, the mod crashes the server on 1.21.3. I know that the mod does not state it is for 1.21.3 but I tried anyways 😅

The version I used: `path_to_grass 1.0.1+1.21`

This is the crash report:
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-11-03 15:44:50
Description: Exception in server tick loop

java.lang.NoSuchFieldError: Class net.minecraft.class_1269 does not have member field 'net.minecraft.class_1269 field_5812'
	at knot//net.minecraft.class_1821.handler$zjd000$path_to_grass$useOnPath(class_1821.java:1048)
	at knot//net.minecraft.class_1821.method_7884(class_1821.java)
	at knot//net.minecraft.class_1799.method_7981(class_1799.java:377)
	at knot//net.minecraft.class_3225.method_14262(class_3225.java:377)
	at knot//net.minecraft.class_3244.method_12046(class_3244.java:1186)
	at knot//net.minecraft.class_2885.method_12547(class_2885.java:42)
	at knot//net.minecraft.class_2885.method_11054(class_2885.java:10)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865)
	at knot//net.minecraft.class_1255.method_18857(class_1255.java:147)
	at knot//net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:829)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:836)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 386235520 bytes (368 MiB) / 803209216 bytes (766 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 1700 Eight-Core Processor          
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21921.1000
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 33724.63
	Virtual memory used (MiB): 24954.01
	Swap memory total (MiB): 17408.00
	Swap memory used (MiB): 379.13
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 99557.14, total: 243562.88
	Space in storage for workdir (MiB): available: 99557.14, total: 243562.88
	JVM Flags: 1 total; -Xmx2G
	Fabric Mods: 
		connected-doors: Connected Doors 1.3+1.21.2
		creeperfireworks: CreeperFireworks 1.0.0.6
			spectrelib: SpectreLib 0.17.2+1.21
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
		fabric-api: Fabric API 0.107.0+1.21.3
			fabric-api-base: Fabric API Base 0.4.49+d21566ae40
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.79+c47b9d4340
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+6c3b5d4940
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+c47b9d4340
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+c47b9d4340
			fabric-command-api-v1: Fabric Command API (v1) 1.2.57+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.36+c47b9d4340
			fabric-commands-v0: Fabric Commands (v0) 0.2.74+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.6+c47b9d4340
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+1ff58ec240
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+c47b9d4340
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+d9873d8b40
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.15+c47b9d4340
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+c47b9d4340
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.6+c47b9d4340
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.10+c47b9d4340
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4340
			fabric-item-api-v1: Fabric Item API (v1) 11.1.6+c47b9d4340
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.16+e7c9ab6640
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+4402f4ee40
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.25+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.13+c47b9d4340
			fabric-message-api-v1: Fabric Message API (v1) 6.0.20+c47b9d4340
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.4+89cb0a4e40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.8+c47b9d4340
			fabric-particles-v1: Fabric Particles (v1) 4.0.9+c47b9d4340
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.3+c47b9d4340
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.1+89cb0a4e40
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.14+c47b9d4340
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+c47b9d4340
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+e82f21f740
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.99+c47b9d4340
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+c47b9d4340
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+c47b9d4340
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fsit: FSit 2.6.2+mc1.21.2
		java: OpenJDK 64-Bit Server VM 21
		jumpprooffarmland: JumpProofFarmland 1.21-1.0.2
		minecraft: Minecraft 1.21.3
		path_to_grass: Path To Grass 1.0.1+1.21
	Server Running: true
	Player Count: 1 / 20; [class_3222['ReloadIt'/68, l='ServerLevel[world]', x=-3.67, y=63.00, z=75.74]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: fabric, fabric-convention-tags-v2, minecart_improvements, redstone_experiments, trade_rebalance, vanilla, winter_drop
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 361607752732494915
	Suppressed Exceptions: ~~NONE~~
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

Hope that helps.

**Comment by PalorderCorporationOfficial** [comment]
Alr first thing check the project build.gradle and check which minecraft version it uses and make a server for that version

**Comment by PalorderCorporationOfficial** [comment]
Alr first thing check the project build.gradle and check which minecraft version it uses and make a server for that version

**Comment by PalorderCorporationOfficial** [comment]
Alr first thing check the project build.gradle and check which minecraft version it uses and make a server for that version

**Comment by PalorderCorporationOfficial** [comment]
You dumb f**k its only for 1.21

**Comment by JMReich** [comment]
Hey, sorry for the late reply, I've been working on my senior project for University. I should have some time to update and fix this in a couple of weeks, eta dec 18th. Thank you for including the crash report!

**Comment by Mqxx** [comment]
Hey, thanks man! No pressure! Focus on your project for University.

**Comment by JMReich** [comment]
Sorry this took so long, my house flooded 5 times this year. Fingers crossed that it won't again. 

Anyway, this has been updated to 1.21.3 and server functionality has been confirmed. 1.21.4 and 1.21.5 updates will come out later today. 

https://modrinth.com/mod/path-to-grass/version/1.0.1+1.21.3

**Comment by Mqxx** [comment]
Thank u 😃
